# -*- coding: utf-8 -*-
"""CHURNGUARD  - RL .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uBTQBrx7JLUdi7e6oiUz-uVCIIF4u5ZY
"""

# ============================================================
# 🎯 ChurnGuard Simplificado — Logistic Regression + SHAP
# ============================================================

# --- 1. Imports ---
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import shap
import warnings
warnings.filterwarnings("ignore")

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    roc_auc_score, f1_score, classification_report,
    confusion_matrix, roc_curve
)
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline

# Estilo visual
sns.set_style("whitegrid")
plt.rcParams["figure.dpi"] = 100
plt.rcParams["font.size"] = 10

# Paleta de cores
COR_CHURN = "#ff6b9d"
COR_FIEL  = "#00d9ff"
COR_DEST  = "#ffa500"

# --- 2. Download do Dataset via Kaggle ---
from google.colab import userdata
os.environ["KAGGLE_API_TOKEN"] = userdata.get("API_KAGGLE")

!kaggle datasets download -d blastchar/telco-customer-churn
!unzip -q telco-customer-churn.zip -d dataset/

print("✅ Dataset baixado e extraído!")

# --- 2. Carrega o CSV ---
df = pd.read_csv("/content/dataset/WA_Fn-UseC_-Telco-Customer-Churn.csv")

print(f"📐 Shape original: {df.shape}")
print(f"📋 Colunas: {df.shape[1]}")
print(f"\n🎯 Distribuição da target:")
print(df["Churn"].value_counts())
print(f"\n📊 Taxa de churn: {(df['Churn']=='Yes').mean()*100:.2f}%")

# --- Limpeza ---
# 1. TotalCharges vem como string (tem espaços vazios)
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

# 2. Preenche NaN (clientes com tenure=0 → cobrança total = 0)
df["TotalCharges"] = df["TotalCharges"].fillna(0)

# 3. Remove customerID (não é feature)
df = df.drop(columns=["customerID"])

# 4. Converte target pra binário
df["Churn"] = (df["Churn"] == "Yes").astype(int)

print(f"\n✅ Após limpeza: {df.shape}")
print(f"🔍 NaN restantes: {df.isnull().sum().sum()}")

# --- 3. EDA Visual ---
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# (a) Distribuição da target
churn_counts = df["Churn"].value_counts()
axes[0,0].pie(churn_counts, labels=["Fiel", "Churn"], autopct="%1.1f%%",
              colors=[COR_FIEL, COR_CHURN], startangle=90,
              wedgeprops={"edgecolor": "white", "linewidth": 2})
axes[0,0].set_title("Distribuição de Churn", fontweight="bold")

# (b) Tenure vs Churn
for churn_val, cor, label in [(0, COR_FIEL, "Fiel"), (1, COR_CHURN, "Churn")]:
    axes[0,1].hist(df[df["Churn"]==churn_val]["tenure"], bins=30,
                   alpha=0.6, color=cor, label=label, edgecolor="white")
axes[0,1].set_xlabel("Tenure (meses)")
axes[0,1].set_ylabel("Frequência")
axes[0,1].set_title("Tenure por Status de Churn", fontweight="bold")
axes[0,1].legend()

# (c) MonthlyCharges vs Churn
for churn_val, cor, label in [(0, COR_FIEL, "Fiel"), (1, COR_CHURN, "Churn")]:
    axes[1,0].hist(df[df["Churn"]==churn_val]["MonthlyCharges"], bins=30,
                   alpha=0.6, color=cor, label=label, edgecolor="white")
axes[1,0].set_xlabel("Mensalidade (US$)")
axes[1,0].set_ylabel("Frequência")
axes[1,0].set_title("Mensalidade por Status de Churn", fontweight="bold")
axes[1,0].legend()

# (d) Churn por tipo de Contrato
contract_churn = df.groupby("Contract")["Churn"].mean().sort_values()
bars = axes[1,1].barh(contract_churn.index, contract_churn.values * 100,
                      color=[COR_FIEL, COR_DEST, COR_CHURN])
axes[1,1].set_xlabel("Taxa de Churn (%)")
axes[1,1].set_title("Churn por Tipo de Contrato", fontweight="bold")
for bar, val in zip(bars, contract_churn.values * 100):
    axes[1,1].text(val + 0.5, bar.get_y() + bar.get_height()/2,
                   f"{val:.1f}%", va="center", fontweight="bold")

plt.tight_layout()
plt.show()

# --- 4. Feature Engineering (sem redundâncias) ---

# 💡 NumServices: quantos serviços o cliente tem (engajamento)
service_cols = [
    "PhoneService", "MultipleLines", "InternetService",
    "OnlineSecurity", "OnlineBackup", "DeviceProtection",
    "TechSupport", "StreamingTV", "StreamingMovies"
]
df["NumServices"] = df[service_cols].apply(
    lambda row: sum(
        v not in ["No", "No internet service", "No phone service"]
        for v in row
    ),
    axis=1
)

# 💡 HasInternet: flag binária
df["HasInternet"] = (df["InternetService"] != "No").astype(int)

# 💡 HasSupport: tem proteção/suporte
df["HasSupport"] = (
    (df["OnlineSecurity"] == "Yes") | (df["TechSupport"] == "Yes")
).astype(int)

# 💡 HasStreaming: perfil consumidor de conteúdo
df["HasStreaming"] = (
    (df["StreamingTV"] == "Yes") | (df["StreamingMovies"] == "Yes")
).astype(int)

print("✅ Features criadas:")
print("   ├── NumServices  → 0 a 9 serviços")
print("   ├── HasInternet  → flag binária")
print("   ├── HasSupport   → flag binária")
print("   └── HasStreaming → flag binária")
print(f"\n📐 Shape: {df.shape}")

# Visualiza as novas features
fig, axes = plt.subplots(1, 4, figsize=(16, 4))
new_features = ["NumServices", "HasInternet", "HasSupport", "HasStreaming"]

for ax, feat in zip(axes, new_features):
    churn_rate = df.groupby(feat)["Churn"].mean() * 100
    bars = ax.bar(churn_rate.index.astype(str), churn_rate.values,
                  color=COR_CHURN, edgecolor="white")
    ax.set_title(f"Churn % por {feat}", fontweight="bold")
    ax.set_ylabel("Taxa de Churn (%)")
    for bar, val in zip(bars, churn_rate.values):
        ax.text(bar.get_x() + bar.get_width()/2, val + 0.5,
                f"{val:.1f}%", ha="center", fontweight="bold")

plt.tight_layout()
plt.show()

# --- 5. Separa X e y ---
X = df.drop(columns=["Churn"])
y = df["Churn"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(f"📦 Treino: {X_train.shape[0]} amostras")
print(f"📦 Teste:  {X_test.shape[0]} amostras")
print(f"\n🎯 Taxa de churn no treino: {y_train.mean()*100:.2f}%")
print(f"🎯 Taxa de churn no teste:  {y_test.mean()*100:.2f}%")

# --- 6. Define colunas numéricas e categóricas ---
num_cols = X_train.select_dtypes(include=np.number).columns.tolist()
cat_cols = X_train.select_dtypes(exclude=np.number).columns.tolist()

print(f"🔢 Numéricas ({len(num_cols)}): {num_cols}")
print(f"🔤 Categóricas ({len(cat_cols)}): {cat_cols}")

# --- Pipeline ---
preprocessor = ColumnTransformer([
    ("num", StandardScaler(), num_cols),
    ("cat", OneHotEncoder(handle_unknown="ignore", drop="first"), cat_cols),
])

model = Pipeline([
    ("pre", preprocessor),
    ("clf", LogisticRegression(
        C=0.1,                          # regularização L2 moderada
        class_weight={0: 1, 1: 2.5},    # peso pra classe minoritária
        max_iter=1000,
        random_state=42,
        solver="lbfgs"
    ))
])

print("\n✅ Pipeline configurado!")

# --- 7. Treina o modelo ---
model.fit(X_train, y_train)

# Cross-validation pra robustez
cv_scores = cross_val_score(model, X_train, y_train, cv=5, scoring="roc_auc")
print(f"📊 ROC-AUC (CV 5-fold): {cv_scores.mean():.4f} (±{cv_scores.std():.4f})")
print(f"   Folds: {[f'{s:.4f}' for s in cv_scores]}")

# Predições no teste
y_proba = model.predict_proba(X_test)[:, 1]
y_pred  = (y_proba >= 0.5).astype(int)

# Métricas
auc = roc_auc_score(y_test, y_proba)
f1  = f1_score(y_test, y_pred)

print(f"\n🎯 ROC-AUC (teste): {auc:.4f}")
print(f"🎯 F1-score (teste): {f1:.4f}")
print(f"\n📋 Classification Report:\n")
print(classification_report(y_test, y_pred, target_names=["Fiel", "Churn"]))

from sklearn.metrics import precision_recall_curve
# --- 8. Plots de Performance ---
fig, axes = plt.subplots(1, 3, figsize=(16, 5))

# (a) Matriz de Confusão
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt="d", cmap="RdPu", ax=axes[0],
            xticklabels=["Fiel", "Churn"], yticklabels=["Fiel", "Churn"],
            cbar=False, annot_kws={"size": 16, "weight": "bold"})
axes[0].set_title("🎯 Matriz de Confusão", fontweight="bold", fontsize=13)
axes[0].set_xlabel("Predito")
axes[0].set_ylabel("Real")

# (b) Curva ROC
fpr, tpr, _ = roc_curve(y_test, y_proba)
axes[1].plot(fpr, tpr, color=COR_CHURN, linewidth=2.5, label=f"AUC = {auc:.4f}")
axes[1].plot([0, 1], [0, 1], "--", color="gray", alpha=0.5)
axes[1].fill_between(fpr, tpr, alpha=0.15, color=COR_CHURN)
axes[1].set_xlabel("Falso Positivo (FPR)")
axes[1].set_ylabel("Verdadeiro Positivo (TPR)")
axes[1].set_title("📈 Curva ROC", fontweight="bold", fontsize=13)
axes[1].legend(loc="lower right", fontsize=11)

# (c) Curva Precision-Recall
prec, rec, _ = precision_recall_curve(y_test, y_proba)
axes[2].plot(rec, prec, color=COR_DEST, linewidth=2.5)
axes[2].fill_between(rec, prec, alpha=0.15, color=COR_DEST)
axes[2].axhline(y_test.mean(), linestyle="--", color="gray", alpha=0.5,
                label=f"Baseline = {y_test.mean():.2f}")
axes[2].set_xlabel("Recall")
axes[2].set_ylabel("Precision")
axes[2].set_title("🎯 Curva Precision-Recall", fontweight="bold", fontsize=13)
axes[2].legend()

plt.tight_layout()
plt.show()

# --- 9. Coeficientes da Regressão Logística (versão limpa) ---
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.patches import Patch

plt.style.use("dark_background")
COR_CHURN = "#ff6b9d"
COR_FIEL  = "#00d9ff"

clf = model.named_steps["clf"]
ohe = model.named_steps["pre"].named_transformers_["cat"]

feature_names = num_cols + list(ohe.get_feature_names_out(cat_cols))
coefs = clf.coef_[0]

# DataFrame com log-odds + % de mudança
df_coef = pd.DataFrame({
    "Feature": feature_names,
    "Coef": coefs,
    "Pct_Change": (np.exp(coefs) - 1) * 100,
    "Abs_Coef": np.abs(coefs)
}).sort_values("Abs_Coef", ascending=False).head(20)

df_plot = df_coef.iloc[::-1].reset_index(drop=True)

# ═══════════════════════════════════════════════════════════
# 📊 PLOT
# ═══════════════════════════════════════════════════════════
fig, ax = plt.subplots(figsize=(14, 10))
fig.patch.set_facecolor("#0e1117")
ax.set_facecolor("#0e1117")

cores = [COR_CHURN if c > 0 else COR_FIEL for c in df_plot["Coef"]]
ax.barh(df_plot["Feature"], df_plot["Coef"],
        color=cores, edgecolor="none", height=0.65)

# Linha do zero (sutil)
ax.axvline(0, color="white", linewidth=0.8, alpha=0.3)

# 🔑 Anotações: log-odds + %
xmax = df_plot["Coef"].max()
xmin = df_plot["Coef"].min()
offset = (xmax - xmin) * 0.018

for i, (coef, pct) in enumerate(zip(df_plot["Coef"], df_plot["Pct_Change"])):
    if coef > 0:
        texto = f"+{coef:.2f}  (+{pct:.0f}%)"
        ax.text(coef + offset, i, texto,
                va="center", ha="left",
                fontsize=10, fontweight="bold", color=COR_CHURN)
    else:
        texto = f"{coef:.2f}  ({pct:.0f}%)"
        ax.text(coef - offset, i, texto,
                va="center", ha="right",
                fontsize=10, fontweight="bold", color=COR_FIEL)

# Limites com folga generosa pros labels
ax.set_xlim(xmin * 1.55, xmax * 1.85)

# Títulos
ax.set_xlabel("Coeficiente (log-odds)  |  % = mudança na chance de churn",
              fontsize=11, color="white", labelpad=12)
ax.set_title("Top 20 Features — Impacto no Churn",
             fontweight="bold", fontsize=15, pad=20, color="white")

# Eixos
ax.tick_params(axis="y", labelsize=10, colors="white", length=0)
ax.tick_params(axis="x", labelsize=10, colors="white")

# 🔥 GRID: só vertical e MUITO suave (sem horizontal!)
ax.grid(False)  # remove tudo primeiro
ax.xaxis.grid(True, alpha=0.1, linestyle="--", linewidth=0.6)
ax.set_axisbelow(True)

# 🔥 Remove TODAS as bordas (estavam criando as linhas horizontais)
for spine in ax.spines.values():
    spine.set_visible(False)

# Legenda
legenda = [
    Patch(facecolor=COR_CHURN, label="↑ Aumenta churn"),
    Patch(facecolor=COR_FIEL,  label="↓ Reduz churn"),
]
ax.legend(handles=legenda, loc="lower right",
          framealpha=0.95, fontsize=11,
          edgecolor="gray", facecolor="#1a1f2e")

plt.tight_layout()
plt.show()

# Taxa de churn REAL por categoria
churn_real = df.groupby("InternetService")["Churn"].agg(["mean", "count"])
churn_real["mean"] = (churn_real["mean"] * 100).round(1)
churn_real.columns = ["Taxa Churn (%)", "Qtd Clientes"]
print(churn_real.sort_values("Taxa Churn (%)", ascending=False))

import seaborn as sns
import matplotlib.pyplot as plt

ct = pd.crosstab(
    [df["InternetService"], df["Contract"]],
    df["Churn"],
    normalize="index"
) * 100

print(ct.round(1))

import matplotlib.pyplot as plt
import numpy as np

plt.style.use("dark_background")
COR_CHURN = "#ff6b9d"
COR_FIEL  = "#00d9ff"

# Dados da sua tabela
internets = ["DSL", "Fiber optic", "No"]
contratos = ["Month-to-month", "One year", "Two year"]
churn_pct = np.array([
    [32.2,  9.3, 1.9],   # DSL
    [54.6, 19.3, 7.2],   # Fibra
    [18.9,  2.5, 0.8],   # Sem internet
])

fig, ax = plt.subplots(figsize=(12, 7))
fig.patch.set_facecolor("#0e1117")
ax.set_facecolor("#0e1117")

x = np.arange(len(internets))
largura = 0.27
cores_contrato = ["#ff6b9d", "#ffd166", "#00d9ff"]

for i, (contrato, cor) in enumerate(zip(contratos, cores_contrato)):
    valores = churn_pct[:, i]
    barras = ax.bar(x + i * largura, valores, largura,
                    label=contrato, color=cor, edgecolor="none")
    for b, v in zip(barras, valores):
        ax.text(b.get_x() + b.get_width()/2, v + 1.2,
                f"{v:.1f}%", ha="center", fontsize=10,
                fontweight="bold", color=cor)

ax.set_xticks(x + largura)
ax.set_xticklabels(internets, fontsize=11, color="white")
ax.set_ylabel("Taxa de Churn (%)", fontsize=11, color="white")
ax.set_title("Churn por Tipo de Internet × Contrato\n"
             "→ O contrato pesa MAIS que o tipo de internet",
             fontweight="bold", fontsize=13, pad=15, color="white")
ax.legend(title="Contrato", loc="upper right",
          framealpha=0.9, facecolor="#1a1f2e")
ax.tick_params(colors="white")
ax.grid(False)
ax.yaxis.grid(True, alpha=0.1, linestyle="--")
ax.set_axisbelow(True)
for spine in ax.spines.values():
    spine.set_visible(False)
ax.set_ylim(0, 65)

plt.tight_layout()
plt.show()

# --- 📊 Nº de Serviços × Churn (versão limpa) ---
import pandas as pd
import matplotlib.pyplot as plt

plt.style.use("dark_background")
ROSA = "#ff6b9d"
AZUL = "#00d9ff"

# Dados agregados
stats = df.groupby("NumServices").agg(
    total=("Churn", "count"),
    churned=("Churn", "sum")
).reset_index()
stats["churn_pct"] = stats["churned"] / stats["total"] * 100
stats["fiel"] = stats["total"] - stats["churned"]

# ═══════════════════════════════════════════════════════════
fig, axes = plt.subplots(1, 2, figsize=(16, 5.5))

# ── (1) Barras empilhadas: composição da base ──
ax = axes[0]
ax.bar(stats["NumServices"], stats["fiel"],
       color=AZUL, label="Fiéis", width=0.7)
ax.bar(stats["NumServices"], stats["churned"], bottom=stats["fiel"],
       color=ROSA, label="Churn", width=0.7)

# Só uma anotação: % de churn no topo
for _, r in stats.iterrows():
    ax.text(r["NumServices"], r["total"] + 25,
            f"{r['churn_pct']:.0f}%",
            ha="center", color="white", fontsize=10, fontweight="bold")

ax.set_xlabel("Nº de Serviços")
ax.set_ylabel("Clientes")
ax.set_title("Composição da Base", fontweight="bold", pad=15)
ax.set_xticks(stats["NumServices"])
ax.legend(loc="upper right", frameon=False)
ax.grid(alpha=0.15, axis="y")
ax.spines[["top", "right"]].set_visible(False)

# ── (2) Linha pura: tendência do churn ──
ax = axes[1]
ax.plot(stats["NumServices"], stats["churn_pct"],
        color=ROSA, linewidth=2.5, marker="o", markersize=9,
        markerfacecolor=ROSA, markeredgecolor="white", markeredgewidth=1.5)

# Anotações simples ao lado de cada ponto
for _, r in stats.iterrows():
    ax.text(r["NumServices"], r["churn_pct"] + 2.5,
            f"{r['churn_pct']:.0f}%",
            ha="center", color="white", fontsize=10)

# Média global (referência)
media = df["Churn"].mean() * 100
ax.axhline(media, color="gray", linestyle="--", linewidth=1, alpha=0.6)
ax.text(stats["NumServices"].max(), media + 1,
        f"média {media:.0f}%", color="gray", fontsize=9, ha="right")

ax.set_xlabel("Nº de Serviços")
ax.set_ylabel("Churn (%)")
ax.set_title("Tendência da Taxa de Churn", fontweight="bold", pad=15)
ax.set_xticks(stats["NumServices"])
ax.set_ylim(0, stats["churn_pct"].max() + 10)
ax.grid(alpha=0.15)
ax.spines[["top", "right"]].set_visible(False)

plt.tight_layout()
plt.show()

# ═══════════════════════════════════════════════════════════
# Tabela resumo (texto simples, sem firula)
print("\nNº Serv | Total | Churn | %")
print("-" * 32)
for _, r in stats.iterrows():
    print(f"   {int(r['NumServices'])}    | {int(r['total']):>5} | "
          f"{int(r['churned']):>5} | {r['churn_pct']:>4.1f}%")

# --- 10. Resumo Final ---
print("=" * 60)
print("  📊 RESUMO EXECUTIVO — MODELO DE CHURN")
print("=" * 60)
print(f"\n📦 Dataset: {df.shape[0]:,} clientes × {df.shape[1]} features")
print(f"🎯 Taxa de churn: {df['Churn'].mean()*100:.2f}%")
print(f"\n🔬 Performance no Teste:")
print(f"   ├── ROC-AUC:  {auc:.4f}")
print(f"   ├── F1-score: {f1:.4f}")
print(f"   └── CV (5-fold AUC): {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")

# Top 5 fatores de risco
top_risk = df_coef[df_coef["Coef"] > 0].head(5)
top_prot = df_coef[df_coef["Coef"] < 0].head(5)

print(f"\n🚨 Top 5 fatores de RISCO (aumentam churn):")
for _, row in top_risk.iterrows():
    print(f"   ├── {row['Feature']:<35} {row['Coef']:+.3f}")

print(f"\n🛡️  Top 5 fatores de PROTEÇÃO (reduzem churn):")
for _, row in top_prot.iterrows():
    print(f"   ├── {row['Feature']:<35} {row['Coef']:+.3f}")

print("\n" + "=" * 60)
print("  ✅ Modelo pronto pra produção!")
print("=" * 60)